import { defineConfig } from "tsup";

export default defineConfig({
	entry: {
		index: "src/index.ts",
		"core/index": "src/core/index.ts",
		"abfrage/index": "src/abfrage/index.ts",
		"upload/index": "src/upload/index.ts",
		"u30/01_2022/index": "src/u30/01_2022/index.ts",
		"u30/07_2026/index": "src/u30/07_2026/index.ts",
		"validation/index": "src/validation/index.ts",
		"jahr_erkl/2023/index": "src/jahr_erkl/2023/index.ts",
		"jahr_erkl/2024/index": "src/jahr_erkl/2024/index.ts",
		"jahr_erkl/2025/index": "src/jahr_erkl/2025/index.ts",
		"l1/2022/index": "src/l1/2022/index.ts",
		"l1/2023/index": "src/l1/2023/index.ts",
		"l1/2024/index": "src/l1/2024/index.ts",
		"l1/2025/index": "src/l1/2025/index.ts",
		"ka1/ab_2016/index": "src/ka1/ab_2016/index.ts",
		"ka1/ab_2022/index": "src/ka1/ab_2022/index.ts",
		"zm/current/index": "src/zm/current/index.ts",
		"kom/current/index": "src/kom/current/index.ts",
		"nova/current/index": "src/nova/current/index.ts",
		"fvan/current/index": "src/fvan/current/index.ts",
		"sb/current/index": "src/sb/current/index.ts",
		"sbs/current/index": "src/sbs/current/index.ts",
		"sbz/current/index": "src/sbz/current/index.ts",
		"rz/current/index": "src/rz/current/index.ts",
		"ueb/current/index": "src/ueb/current/index.ts",
		"digi/current/index": "src/digi/current/index.ts",
		"stab/current/index": "src/stab/current/index.ts",
		"bet/current/index": "src/bet/current/index.ts",
		"vat/current/index": "src/vat/current/index.ts",
		"due/current/index": "src/due/current/index.ts",
		"vatab/current/index": "src/vatab/current/index.ts",
		"komu/current/index": "src/komu/current/index.ts",
		"tvw/current/index": "src/tvw/current/index.ts",
		"soer/current/index": "src/soer/current/index.ts",
		"vpdgd/v2_0/index": "src/vpdgd/v2_0/index.ts",
		"cli/index": "src/cli/index.ts",
		"mcp/index": "src/mcp/index.ts",
		"mcp/server": "src/mcp/server.ts",
	},
	format: ["esm"],
	dts: true,
	sourcemap: true,
	clean: true,
	target: "node20",
	splitting: false,
});
